apiVersion: skaffold/v4beta3 
kind: Config 

build: 
  artifacts:
    # - image: kse-my-first-streams
    #   context: apps/my_first_streams
    - image: ksa-gradleapp     # 생성(build)할 이미지 이름(registry) 지정
      context: apps/gradleapp  # 이미지화 대상 app 경로
    #- image: ksa-mavenapp
    #  context: apps/mavenapp

deploy:
  # skaffold로 deploy동작이 포함된 명령어 실행시, helm으로 이를 수행하겠다는 뜻
  helm:  
    releases:
      - name: testreleasename
        chartPath: helm         # Helm 차트 경로
        skipBuildDependencies: true
        #valueFiles:            # Helm 실행시 사용될 value 파일
        #setValueTemplates:     # 추가로 설정할 value

profiles:
  # skaffold 실행시 profile을 선택하여 위 deploy 설정에 추가할 수 있다.
  # skaffold dev -p my_first_streams
  - name: my_first_streams
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - configs/my_first_streams.yaml
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          # skaffold 기능: 로컬 레지스트리에 방금 build된 이미지의 정보를 불러오기
          # suffix는 build.aritfacs의 이름과 맞춰야 하며 -는 _로 바꾼다.
          # value 우선순위: cli options > skaffold.yaml > value파일 > default value
          streams.image.registry: '{{ .IMAGE_DOMAIN_kse_my_first_streams }}'
          streams.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_kse_my_first_streams }}'
          streams.image.tag: '{{ .IMAGE_TAG_kse_my_first_streams }}'
  - name: gradleapp
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - configs/gradleapp.yaml
  - name: mavenapp
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - configs/mavenapp.yaml


  